version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running tests..."

workflows:
  version: 2
  my-workflow:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
