apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pac-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "push, pull_request"   # 指定触发事件
spec:
  pipelineSpec:               # 直接在 PipelineRun 内定义 pipeline
    tasks:
      - name: run-hello
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi8/ubi-minimal
              script: |
                #!/bin/sh
                echo "Hello from Pipelines as Code!"