apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pac-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"      # 加方括号
    pipelinesascode.tekton.dev/on-target-branch: "[master, main]"    # 必须有这个
spec:
  pipelineSpec:
    tasks:
      - name: run-hello
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi8/ubi-minimal
              script: |
                #!/bin/sh
                echo "Hello from Pipelines as Code!"